export const COUNTRIES = [
  {
    code: "ES",
    name: "España",
    currency: "EUR",
    locale: "es-ES",
    zone: "europe",
  },
  {
    code: "MX",
    name: "México",
    currency: "MXN",
    locale: "es-MX",
    zone: "latam",
  },
  {
    code: "US",
    name: "Estados Unidos",
    currency: "USD",
    locale: "en-US",
    zone: "north-america",
  },
  {
    code: "CO",
    name: "Colombia",
    currency: "COP",
    locale: "es-CO",
    zone: "latam",
  },
  {
    code: "AR",
    name: "Argentina",
    currency: "ARS",
    locale: "es-AR",
    zone: "latam",
  },
  {
    code: "CL",
    name: "Chile",
    currency: "CLP",
    locale: "es-CL",
    zone: "latam",
  },
  {
    code: "BR",
    name: "Brasil",
    currency: "BRL",
    locale: "pt-BR",
    zone: "latam",
  },
  {
    code: "FR",
    name: "Francia",
    currency: "EUR",
    locale: "fr-FR",
    zone: "europe",
  },
  {
    code: "DE",
    name: "Alemania",
    currency: "EUR",
    locale: "de-DE",
    zone: "europe",
  },
  {
    code: "IT",
    name: "Italia",
    currency: "EUR",
    locale: "it-IT",
    zone: "europe",
  },
  {
    code: "PT",
    name: "Portugal",
    currency: "EUR",
    locale: "pt-PT",
    zone: "europe",
  },
  {
    code: "GB",
    name: "Reino Unido",
    currency: "GBP",
    locale: "en-GB",
    zone: "europe",
  },
  {
    code: "CA",
    name: "Canadá",
    currency: "CAD",
    locale: "en-CA",
    zone: "north-america",
  },
  {
    code: "JP",
    name: "Japón",
    currency: "JPY",
    locale: "ja-JP",
    zone: "asia",
  },
  {
    code: "KR",
    name: "Corea del Sur",
    currency: "KRW",
    locale: "ko-KR",
    zone: "asia",
  },
  {
    code: "CN",
    name: "China",
    currency: "CNY",
    locale: "zh-CN",
    zone: "asia",
  },
  {
    code: "AU",
    name: "Australia",
    currency: "AUD",
    locale: "en-AU",
    zone: "oceania",
  },
  {
    code: "IN",
    name: "India",
    currency: "INR",
    locale: "hi-IN",
    zone: "asia",
  },
  {
    code: "AE",
    name: "Emiratos Árabes",
    currency: "AED",
    locale: "ar-AE",
    zone: "middle-east",
  },
  {
    code: "ZA",
    name: "Sudáfrica",
    currency: "ZAR",
    locale: "en-ZA",
    zone: "africa",
  },
  {
    code: "PE",
    name: "Perú",
    currency: "PEN",
    locale: "es-PE",
    zone: "latam",
  },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["code"];
export type Zone = (typeof COUNTRIES)[number]["zone"];
